### PR TITLE
add styles, edit copy

### PR DESCRIPTION
**Pull request by ianstormtaylor**
Added basic typography styles to get the idea started. Need to get the files together to make that logo parallaxing concept happen nicely.

Also edited down the copy from the Readme pretty heavily to try and keep it really concise and appeal to people who know a bit less about Component and the features.

### CODE REVIEW

**Comment by matthewmueller** [comment]
wow, i'm drooling

**Comment by matthewmueller** [comment]
I wonder if there's something we can do to keep the readme's consistent. i think this is fine for now though and maybe they'll just diverge.

**Comment by ianstormtaylor** [comment]
Oh yeah, I think we should axe the exact same content from the readme, and instead link right at the top of the site, and have a shorter summary of the ideals before jumping into repo-specific things. Does that seem good?

**Comment by matthewmueller** [comment]
yep that works for me!

**Pull request merged**
