### PR TITLE
add hidden search field for kicks

### PR DESCRIPTION
**Pull request by ianstormtaylor**
Added a hidden search field so that if @dominicbarnes or anyone works on a registry system we can be ready to implement it on the site! Imagining there would be a slice in the page that would open up horizontally and dropdown with a list of modules.

Here's it un-hidden:

### CODE REVIEW

**Comment by dominicbarnes** [comment]
Dude... that looks awesome

**Comment by ianstormtaylor** [comment]
thanks man!

**Comment by yields** [comment]
amazing.

**Comment by matthewmueller** [comment]
thanks!

**Pull request closed without merging**
