### PR TITLE
add start of header, still needs logo and collapsing logic

### PR DESCRIPTION
**Pull request by ianstormtaylor**
Adding the start of the header. Found this image on Unsplash and it kinda of fit nicely I thought and has a good color scheme, and had a nice tie with the duo of people in the image, but open to different ideas.

Here's the down:

And then up you'd just see the very top of it (and there would be a search form and a smaller logo):

Still need to get the logo file created in that other repo, going to use the `logo/logo` pattern if that's cool to make it modular and require it in. I think we'll need a description and maybe even the name towards the bottom of the image, because the graphic logo by itself doesn't given people enough information on first sight.
- [x] Add white logo in middle.
- [x] Add "Duo" and tagline at bottom.
- [ ] Add search box.
- [x] Add "View on GitHub" banner in top-right.
- [ ] Add Javascript logic to properly transition between regular and collapsed states.

### CODE REVIEW

**Comment by matthewmueller** [comment]
Oh I love this picture. I like that there's 2 people, a duo, if you will ;-). Not exactly sure how it'll look with a whited out DUO (if it'll be cutting someone off or whatnot)

Some other options that I like from unsplash. maybe doesn't work with a white logo, but we could modify that:

hay

sunset

**Comment by ianstormtaylor** [comment]
Kk, pull request updated and ready to merge I think. cc @MatthewMueller

**Comment by ianstormtaylor** [comment]
Then we can focus on copy. And a few odds and ends like favicon. Also included that logo for you right in `lib/` but feel free to move out.

**Comment by matthewmueller** [comment]
wowwww, rebase plz? :-)

**Comment by ianstormtaylor** [comment]
Ah, so I ran into an issue, I accidentally committed some big PSDs, but then needed to erase them from the history, and probably rewrote all commits instead of just the ones with them in it? Might be easiest just to merge it in instead of figure out what Gitting went on :) let me know though

**Comment by matthewmueller** [comment]
absolutely incredible. better than i could have ever imagined. great work @ianstormtaylor!

**Comment by ianstormtaylor** [comment]
thanks dude, happy to help!

**Pull request merged**
